name: ci

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Install dependencies
        run: pnpm install

      - name: Type check
        run: pnpm type

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
